library/urls.py
from django.conf.urls import url

from library.alias.views import AliasCreateView, AliasesView
from library.author.views import AuthorCreateView, AuthorsView
from library.authors_works.views import WorkAuthorsView, WorkAuthorsCreateView
from library.publication.views import PublicationCreateView, \
    PublicationsView
from library.translations.views import TranslationsView, TranslationCreateView
from library.work.views import WorksView, WorkCreateView
from library.writings.views import WritingsView, WritingCreateView
from . import views

app_name = 'library'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^query$', views.query_view, name='query'),
    url(r'^trigger-switch$', views.trigger_switch, name='trigger-switch'),

    url(r'^authors$', AuthorsView.as_view(), name='authors'),
    url(r'^author/create$', AuthorCreateView.as_view(), name='author_create'),

    url(r'^work-authors$', WorkAuthorsView.as_view(), name='work-authors'),
    url(r'^work-author/create$', WorkAuthorsCreateView.as_view(), name='work-authors_create'),

    url(r'^aliases$', AliasesView.as_view(), name='aliases'),
    url(r'^alias/create$', AliasCreateView.as_view(), name='alias_create'),

    url(r'^publications$', PublicationsView.as_view(), name='publications'),
    url(r'^publications/create$', PublicationCreateView.as_view(), name='publication_create'),

    url(r'^works$', WorksView.as_view(), name='works'),
    url(r'^works/create$', WorkCreateView.as_view(), name='work_create'),

    url(r'^writings$', WritingsView.as_view(), name='writings'),
    url(r'^writings/create$', WritingCreateView.as_view(), name='writing_create'),

    url(r'^translations$', TranslationsView.as_view(), name='translations'),
    url(r'^translations/create$', TranslationCreateView.as_view(), name='translation_create'),
]

library/templates/library/base.html
{% load staticfiles %}
{% load django_bootstrap_breadcrumbs %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css"
          integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'library/css/style.css' %}">
    {% block extrastyle %}{% endblock %}
</head>
<body>

{% block breadcrumbs %}
    {% breadcrumb "Home" "/" %}
{% endblock %}
{% block content %}
    {% render_breadcrumbs %}
{% endblock %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"
        integrity="sha384-THPy051/pYDQGanwU6poAc/hOdQxjnOEXzbT+OuUAFqNqFjL+4IGLBgCJC3ZOShY"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"
        integrity="sha384-Plbmg8JY28KFelvJVai01l8WyZzrYWG825m+cZ0eDDS1f7d/js6ikvy1+X+guPIB"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js"
        integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU"
        crossorigin="anonymous"></script>
<script src="{% static 'library/js/main.js' %}"></script>
{% block extrascript %}{% endblock %}
</body>
</html>

library/templates/library/index.html
{% extends 'library/base.html' %}
{% block content %}
    {{ block.super }}
    <div class="container">
        <div class="alert alert-success alert-dismissible fade in" role="alert" style="display: none">
            <button type="button" class="close" data-hide="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            <strong>Well done! </strong><span></span>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <h3>Library</h3>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-5">
                <div class="row">
                    <h3>Queries</h3>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-5">
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:aliases' %}">Aliases</a>
                </div>
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:authors' %}">Authors</a>
                </div>
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:works' %}">Works</a>
                </div>
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:work-authors' %}">WorkAuthors</a>
                </div>
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:writings' %}">Writings</a>
                </div>
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:publications' %}">Publications</a>
                </div>
                <div class="list-group">
                    <a class="list-group-item list-group-item-action"
                       href="{% url 'library:translations' %}">Translations</a>
                </div>
            </div>
            <div class="col-sm-1"></div>
            <div class="col-sm-5">
                <div class="row">
                    <h5>Find info about translations</h5>
                    <form class="form-inline" action="{% url 'library:query' %}" method="get">
                        <div class="form-group">
                            <input hidden name="query_type" value="1"/>
                            <label for="inputName">Surname</label>
                            <input name="surname" type="text" class="form-control" id="inputName" placeholder="Smith"
                                   required>
                        </div>
                        <button type="submit" class="btn btn-primary">Find</button>
                    </form>
                </div>
                <div class="row">
                    <a class="btn btn-primary btn-block" href="{% url 'library:query' %}?query_type=2" role="button">Find
                        authors with two and more aliases</a>
                </div>
                <div class="row">
                    <a class="btn btn-primary btn-block" href="{% url 'library:query' %}?query_type=3" role="button">Find
                        count of works for each author</a>
                </div>
                <div class="row">
                    <h3>Triggers</h3>
                </div>
                <div class="row"></div>
                <div class="row">
                    <label class="form-check-inline">
                        <input class="form-check-input" type="checkbox" id="trigger1"
                               {% if trigger_status.0 %}checked{% endif %}> Trigger 1
                    </label>
                    <label class="form-check-inline">
                        <input class="form-check-input" type="checkbox" id="trigger2"
                               {% if trigger_status.1 %}checked{% endif %}> Trigger 2
                    </label>
                    <label class="form-check-inline">
                        <input class="form-check-input" type="checkbox" id="trigger3"
                               {% if trigger_status.2 %}checked{% endif %}> Trigger 3
                    </label>

                </div>
            </div>
        </div>
    </div>
{% endblock %}

library/templates/library/object_form.html
{% extends 'library/objects.html' %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb 'Add '|add:model_name '' %}
{% endblock %}
{% block content %}
    {% render_breadcrumbs %}
    <div class="container">
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>{{ message.level_tag|title }}: </strong> {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
        <div class="row">
            <div class="col-sm-6">
                <form method="post">
                    {% crispy form form.helper %}
                    <input class="btn btn-outline-primary pull-xs-right" type="submit" value="Save"/>
                </form>

            </div>
        </div>
    </div>
{% endblock %}

library/templates/library/objects.html
{% extends 'library/base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% load crispy_forms_tags %}

{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb model_name_plural|title 'library:'|add:model_name_plural %}
{% endblock %}
{% block content %}
    {{ block.super }}
    <div class="container">
        <div class="row">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <strong>{{ message.level_tag|title }}:</strong> {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
            <h3>{{ model_name_plural|title }}
                {% with 'library:'|add:model_name|add:'_create' as create_url %}
                    <a class="btn btn-primary pull-xs-right btn-round"
                       href="{% url create_url %}"
                       role="button">Add {{ model_name }}</a>
                {% endwith %}
            </h3>
        </div>
        <div class="row">
            <div class="col-sm-{% firstof col_size 12 %}">
                <form method="post">
                    {% crispy formset helper %}
                    <div class="row">
                        <input class="btn btn-outline-primary pull-xs-right" type="submit" value="Save"/>
                        {% if is_paginated %}
                            <ul class="pagination">
                                {% if page_obj.has_previous %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page_obj.previous_page_number }}">&laquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                                {% endif %}
                                {% for i in paginator.page_range %}
                                    {% if page_obj.number == i %}
                                        <li class="page-item active"><span class="page-link">{{ i }} <span
                                                class="sr-only">(current)</span></span></li>
                                    {% else %}
                                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                                    {% endif %}
                                {% endfor %}
                                {% if page_obj.has_next %}
                                    <li class="page-item"><a class="page-link"
                                                             href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                                {% endif %}
                            </ul>

                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

library/templates/library/query_result.html
{% extends 'library/base.html' %}
{% load django_bootstrap_breadcrumbs %}
{% block breadcrumbs %}
    {{ block.super }}
    {% breadcrumb "Query result" "" %}
{% endblock %}
{% block content %}
    {{ block.super }}
    <div class="container">
        <div class="row">
            <table class="table table-stripped table-sm">
                <thead>
                {% for r in result.0 %}
                    <th>{{ r }}</th>
                {% endfor %}
                </thead>
                {% for row in result.1 %}
                    <tr>
                        {% for col in row %}
                            <td>{{ col }}</td>
                        {% endfor %}
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
{% endblock %}